name: "personal_website"
description: "personal website for my own website"
code: 1
version: "v1"
application_id: "f168fe80-fed3-4919-9909-d3749226e22e"

permissions:
  - name: "test"
    description: "test"
    code: 1

  - name: "read"
    description: "read"
    code: 2

  - name: "write"
    description: "write"
    code: 3